pipeline {
    agent any 

    options {
        timestamps()
    }

    environment {
        NODEJS_TOOL = 'node_18'
        NG_CLI_ANALYTICS = 'ci'
    }

    stages {
        stage('Install') {
            steps {
                withEnv(["PATH=${tool env.NODEJS_TOOL}/bin:${env.PATH}"]) {
                    sh 'npm ci'
                }
            }
        }
    }
}
