pipeline {
    agent {
        docker {
            image 'node:12-bullseye'
            args '-u root:root'
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Install') {
            steps {
                dir('microservice-ui') {
                    sh 'npm ci'
                }
            }
        }
    }
}
